### ISSUE TITLE
Labels test data

### ISSUE THREAD

**Issue by lcmmichielsen** [vagarwal87/Xpresso#1]
Hi,

Thanks for the all the documentation and the google colab, very useful! When I compare the results I get from the google colab from the 'Train Xpresso model for human data' section with Figure 2B from the paper, I get slightly different results. The actual values range between -1 and 3, but the labels in test.h5 range between -1.5 and 2.1. How can this difference be explained? Am I missing an important scaling step here?

**Comment by vagarwal87** [comment]
Hello,

Yes, they were treated slightly differently. The reason the scale is a bit different has to do with the Line 170 of the following script:

https://github.com/vagarwal87/Xpresso/blob/b5d1da2b7f7e9376e8b6eca2b6cc73cd361734a3/Fig1_S2/setup_training_files.py#L170

The 0th column of this table is the Expression level, which is Z-score transformed.

Hope that helps!
