### ISSUE TITLE
Median calculation of gene expression levels

### ISSUE THREAD

**Issue by doveppp** [vagarwal87/Xpresso#5]
Hello, I calculated the median of gene expression data using the method mentioned in the paper, but there are some differences with your data. Why is that?
Here is my code:

```python
import h5py
import pandas as pd
import numpy as np
file = h5py.File("./Dataset/pM10Kb_1KTest/train.h5")
df = pd.read_csv("./Dataset/57epigenomes.RPKM.pc", delimiter="\t", index_col=False)
df.set_index("gene_id", inplace=True)
df.drop("E000", axis=1, inplace=True)

for i in range(10):
    gene_name, label = file["geneName"][i].decode(), file["label"][i]
    print(
        gene_name,
        label,
        np.median(np.log10(df.loc[gene_name].values + 0.1)),
    )

```

output:
```
ENSG00000163687 -1.1226947617112275 -0.6882513061024739
ENSG00000118257 0.3762985601956982 0.6835448727838647
ENSG00000091513 -1.0362079585882409 -0.6097693335691412
ENSG00000183036 -0.7529048760994538 -0.35008515714841393
ENSG00000171105 0.5229501944167456 0.8183093833857156
ENSG00000244057 -1.4632121967076765 -1.0
ENSG00000255501 -1.4632121967076765 -1.0
ENSG00000126773 0.6730196517984761 0.9556608492105295
ENSG00000187957 -0.35692683216539983 0.01265293263238513
ENSG00000068097 0.6647014439766871 0.9481552358329275
```

**Comment by vagarwal87** [comment]
Hi, Please find the code to reproduce the exact medians available here: https://github.com/vagarwal87/Xpresso/blob/master/Fig1_S2/process_RNAseq.R

**Comment by doveppp** [comment]
Thanks. I got the correct median, but how are the labels in the train.h5 file calculated from the median?

**Comment by vagarwal87** [comment]
in the train.h5 file, it's the same one that's been z-score transformed...once you take the z-score it should be consistent. It shouldn't matter too much though, if you take the correlation between your median and the z-score version, you'll see the correlation should = 1

**Comment by doveppp** [comment]
Thank you very much for your reply!
